# Generated by Django 4.0.3 on 2024-09-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('service', '0002_alter_service_status_alter_servicecategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
