# Generated by Django 4.0.3 on 2024-09-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('service', '0003_servicecategory_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
