# Generated by Django 4.0.3 on 2023-07-05 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Не активный')], default='active', max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод')], max_length=255, verbose_name='Метод оплаты')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
        migrations.CreateModel(
            name='CashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('income', 'Приход'), ('outcome', 'Расход')], max_length=255, verbose_name='Тип оплаты')),
                ('model_type', models.CharField(choices=[('patient', 'Пациент'), ('service', 'Услуги')], max_length=255, verbose_name='Категория')),
                ('model_id', models.IntegerField(default=0, verbose_name='Причина')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(null=True, verbose_name='Контент')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод')], max_length=255, verbose_name='Метод оплаты')),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.cash', verbose_name='Касса')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Операция по кассе',
                'verbose_name_plural': 'Операции по кассе',
            },
        ),
    ]
