# Generated by Django 4.0.3 on 2024-09-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Не активный')], default='active', max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод')], max_length=255, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
        migrations.CreateModel(
            name='CashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('income', 'Приход'), ('outcome', 'Расход')], max_length=255, verbose_name='Тип оплаты')),
                ('category', models.CharField(choices=[('service_payment', 'Оплата за санацию (услугу)'), ('staff_salary', 'Зарплата персонала'), ('service_expense', 'Расход на услугу'), ('rent_and_utility_bills', 'Аренда и коммунальные платежи'), ('purchase_medical_materials', 'Закупка медицинских материалов')], default='service_payment', max_length=255, verbose_name='Категория')),
                ('model_type', models.CharField(choices=[('patient', 'Пациент'), ('service', 'Услуги'), ('user', 'Сотрудник'), ('order', 'Санация')], max_length=255, verbose_name='Категория')),
                ('model_id', models.IntegerField(default=0, verbose_name='Причина')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(null=True, verbose_name='Контент')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод')], max_length=255, verbose_name='Метод оплаты')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.cash', verbose_name='Касса')),
            ],
            options={
                'verbose_name': 'Операция по кассе',
                'verbose_name_plural': 'Операции по кассе',
            },
        ),
    ]
