# Generated by Django 4.0.3 on 2024-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('cash', '0002_cash_branch_cashlog_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
