# Generated by Django 4.0.3 on 2024-09-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_alter_cash_branch_alter_cashlog_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashlog',
            name='category',
            field=models.CharField(choices=[('service_payment', 'Оплата за санацию (услугу)'), ('staff_salary', 'Зарплата персонала'), ('service_expense', 'Расход на услугу'), ('rent_and_utility_bills', 'Аренда и коммунальные платежи'), ('purchase_medical_materials', 'Закупка медицинских материалов')], default='service_payment', max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='model_type',
            field=models.CharField(choices=[('patient', 'Пациент'), ('service', 'Услуги'), ('user', 'Сотрудник'), ('order', 'Санация')], max_length=255, verbose_name='Категория'),
        ),
    ]
