# Generated by Django 4.1 on 2022-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255, verbose_name="Ф.И.О")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="patient", verbose_name="Фото"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doc_type",
                    models.CharField(max_length=255, verbose_name="Тип документа"),
                ),
                (
                    "doc_series",
                    models.CharField(max_length=255, verbose_name="Серия документа"),
                ),
                (
                    "doc_number",
                    models.CharField(max_length=255, verbose_name="Номер документа"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Статус")),
            ],
            options={"verbose_name": "Пациент", "verbose_name_plural": "Пациенты",},
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата записи")),
                ("content", models.TextField(null=True, verbose_name="Контент")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Запись на прием",
            },
        ),
    ]
