# Generated by Django 4.1 on 2022-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_birthday_alter_patient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doc_type",
            field=models.CharField(
                choices=[("passport", "Паспорт"), ("metrics", "Метрика")],
                max_length=255,
                verbose_name="Тип документа",
            ),
        ),
    ]
