# Generated by Django 4.1 on 2022-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_alter_patient_doc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[("active", "Активный"), ("disabled", "Не активный")],
                default="active",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
