# Generated by Django 4.1 on 2022-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_alter_patient_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doc_number",
            field=models.CharField(max_length=7, verbose_name="Номер документа"),
        ),
    ]
