# Generated by Django 4.1 on 2022-08-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_doc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=255, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
