# Generated by Django 4.1 on 2022-09-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0007_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='registrar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='registrar', to=settings.AUTH_USER_MODEL, verbose_name='Регистрировал'),
            preserve_default=False,
        ),
    ]
