# Generated by Django 4.1 on 2022-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_record_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего визита стоматолога'),
        ),
    ]
