# Generated by Django 4.0.3 on 2022-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chat_id',
            field=models.BigIntegerField(default=0, verbose_name='Телеграм айди'),
        ),
    ]
