# Generated by Django 4.0.3 on 2022-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
