# Generated by Django 4.0.3 on 2024-09-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('patient', '0011_record_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
