# Generated by Django 4.0.3 on 2024-09-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('patient', '0012_patient_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
