# Generated by Django 4.1 on 2022-08-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="end_time",
            field=models.TimeField(null=True, verbose_name="Время конца работы"),
        ),
        migrations.AlterField(
            model_name="user",
            name="start_time",
            field=models.TimeField(null=True, verbose_name="Время начала работы"),
        ),
    ]
