# Generated by Django 4.1 on 2022-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Активный"), ("disabled", "Не активный")],
                default="active",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
