# Generated by Django 4.1 on 2022-08-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Статус")),
                ("content", models.TextField(null=True, verbose_name="Контент")),
            ],
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки",},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Статус")),
                ("price", models.FloatField(default=0, verbose_name="Цена")),
                ("count", models.IntegerField(default=0, verbose_name="Кол-во")),
                ("amount", models.FloatField(default=0, verbose_name="Сумма")),
                ("tooth", models.IntegerField(default=0, verbose_name="Номер зуба")),
                ("content", models.TextField(null=True, verbose_name="Контент")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент заявки",
                "verbose_name_plural": "Элементы заявок",
            },
        ),
    ]
