# Generated by Django 4.0.3 on 2024-09-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('process', 'В процессе'), ('done', 'Завершённый'), ('canceled', 'Отменённый')], default='process', max_length=255, verbose_name='Статус')),
                ('content', models.TextField(null=True, verbose_name='Жалобы')),
                ('diagnosis', models.TextField(null=True, verbose_name='Диагноз')),
                ('inspection', models.TextField(null=True, verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Не активный')], default='active', max_length=255, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('tooth', models.IntegerField(default=0, verbose_name='Номер зуба')),
                ('content', models.TextField(null=True, verbose_name='Контент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заявки',
                'verbose_name_plural': 'Элементы заявок',
            },
        ),
    ]
