# Generated by Django 4.1 on 2022-08-28 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0001_initial"),
        ("service", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="registrar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Регистрировал",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="service.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Доктор",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="patient.patient",
                verbose_name="Пвциент",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="registrar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Регистрировал",
            ),
        ),
    ]
