# Generated by Django 4.1 on 2022-09-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_last_visit'),
        ('order', '0004_alter_order_status_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient', verbose_name='Пациент'),
        ),
    ]
