# Generated by Django 4.0.3 on 2022-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diagnosis',
            field=models.TextField(null=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='order',
            name='inspection',
            field=models.TextField(null=True, verbose_name='Осмотр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(null=True, verbose_name='Жалобы'),
        ),
    ]
